name: Deploy LMS Frontend with SonarQube Quality Gate

on:
  push:
    branches:
      - main

jobs:
  analyze-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SonarQube Analysis
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=LMS_Frontend
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonar.leran.xyz
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Wait for Quality Gate result
      id: qualitygate
      uses: sonarsource/sonarqube-quality-gate-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonar.leran.xyz

    - name: Check Quality Gate Status
      run: |
        echo "Quality Gate Status: ${{ steps.qualitygate.outputs.quality_gate_status }}"
        if [[ "${{ steps.qualitygate.outputs.quality_gate_status }}" != "PASSED" ]]; then
          echo "❌ SonarQube Quality Gate failed. Stopping deployment."
          exit 1
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Ensure remote folder & fix permissions
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo mkdir -p /var/www/html/LMS_frontend
          sudo rm -rf /var/www/html/LMS_frontend/*
          sudo chown -R ${{ secrets.EC2_USERNAME }}:www-data /var/www/html/LMS_frontend
          sudo chmod -R 775 /var/www/html/LMS_frontend

    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "dist/*"
        target: "/var/www/html/LMS_frontend"
